services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres_flight_ticket_service
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${POSTGRES_FLIGHT_DATA_PATH}:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
