services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres_auth_service
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${POSTGRES_AUTH_DATA_PATH}:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB_NAME}

  redis:
    image: redis:latest
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ~/apps/redis:/root/redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}